apiVersion: v1   # version of kubernetes api used to create the object
kind: Secret   # the type of Kubernetes objects to be created
metadata:   # data that helps uniquely identify an object 
  name: mongodb-secret   
type: Opaque
data:   # user-defined key-value pairs 
  mongo-root-username: dXNlcm5hbWU=   # in kubernetes secret yaml files, values must be base 64 encoded
  mongo-root-password: cGFzc3dvcmQ=
