# select the api version and type of object/service
apiVersion: v1
kind: Service

# metadata for name
metadata:
  name: nodeapp-svc
  namespace: default 
# specification to include ports selector to connect to the deployment
spec:
  ports:
  - nodePort: 31455
    port: 80
    protocol: TCP
    targetPort: 3000

  # define the selector
  selector:
    app: nodeapp   # this label connects this service to the deployment

  # creating a loadbalancer type of deployment
  type: LoadBalancer