apiVersion: apps/v1   # which api to use for deployment
kind: Deployment   # want to create Deployment service

# what would you like to call it 
metadata:
  name: nodeapp-deploy   # naming the deployment
spec:
  selector:
    matchLabels:
      app: nodeapp  # look for this label to match with k8 service

  # create a replica set of this with 2 instances/pods
  replicas: 1   # k8 will ensure that this number of replicas is consistently running 

  # template to use it's label for k8 service to launch in the browser
  template: 
    metadata:
      labels:
        app: nodeapp   # this label connects to the service or any other k8 components

  # define the container spec
    spec:
      containers:
      - name: nodeapp
        image: fahimtq1/eng122-fahim-node-app:latest
        ports: 
        - containerPort: 3000