version: "3.9"
services:
  db:
    build: ./db
    ports:
      - "27017:27017"


  app:
    build: ./nodeapp/app
    restart: always
    ports:
      - "3000:3000"
    environment:   # specifies an evironment variable in the app container
      - DB_HOST=mongodb://db:27017/posts   
    depends_on:   # expresses dependency of app service on db service- db service will start fast
      - db